(() => {
  "use strict";

  const GAME_VERSION = "0.9.1";

  const LEVELS = [
    { name: "Waldweg bei Seiffen", short: "Seiffen", subtitle: "Zwischen Fichten und Werkstätten", accent: "#3f8a65", sky: ["#8ed3cf", "#d9efe1"], ground: "#537b4a", mood: "forest", backdrop: "level-01" },
    { name: "Dorf der Lichter", short: "Lichterdorf", subtitle: "Fachwerk, Fenster und Figuren", accent: "#d9993b", sky: ["#88c7c7", "#f8dfaa"], ground: "#687744", mood: "village", backdrop: "level-02" },
    { name: "Silberner Stollen", short: "Silberstollen", subtitle: "Kristalle unter alten Balken", accent: "#5b83a2", sky: ["#66859a", "#b9d0ca"], ground: "#4f665c", mood: "mine", backdrop: "level-03" },
    { name: "An der Zschopau", short: "Zschopautal", subtitle: "Über Wasser und Mühlräder", accent: "#2c8c9c", sky: ["#76c8d0", "#d8efe6"], ground: "#4d7b55", mood: "river", backdrop: "level-04" },
    { name: "Bimmelbahn-Bogen", short: "Bimmelbahn", subtitle: "Mit Volldampf über die Höhen", accent: "#ae4c4d", sky: ["#98ced2", "#f5e2b4"], ground: "#5f784c", mood: "rail", backdrop: "level-05" },
    { name: "Annaberger Dächer", short: "Annaberg", subtitle: "Hoch über Gassen und Giebeln", accent: "#b6604e", sky: ["#7fb9c8", "#f6d2a5"], ground: "#596d50", mood: "rooftops", backdrop: "level-06" },
    { name: "Schwibbogen-Nacht", short: "Lichterbogen", subtitle: "Ein Weg im warmen Kerzenschein", accent: "#d6a53d", sky: ["#213958", "#855f75"], ground: "#384c4c", mood: "night", backdrop: "level-07" },
    { name: "Die Greifensteine", short: "Greifensteine", subtitle: "Kühne Sprünge durch Granit", accent: "#8c6d55", sky: ["#81b7bd", "#e5ddd0"], ground: "#646c50", mood: "rocks", backdrop: "level-08" },
    { name: "Über Wolkenstein", short: "Wolkenstein", subtitle: "Burgenblick und Wolkensprünge", accent: "#7c659c", sky: ["#88bddd", "#f0e8d2"], ground: "#59725a", mood: "castle", backdrop: "level-09" },
    { name: "Gipfel am Fichtelberg", short: "Fichtelberg", subtitle: "Das große Finale über den Wolken", accent: "#c15455", sky: ["#69abc9", "#f8e8c5"], ground: "#4d725c", mood: "summit", backdrop: "level-10" },
    { name: "Der geflutete Stollen", short: "Tauchstollen", subtitle: "Bonus: durch versunkene Schächte", accent: "#47c8d2", sky: ["#0d4658", "#2f8991"], ground: "#365c5e", mood: "underwater", backdrop: "level-11", underwater: true, bonus: true },
    { name: "Die Sonnenbahn", short: "Sonnenbahn", subtitle: "Bonus: Lade die leise Bergbahn", accent: "#e7a842", sky: ["#81c9e1", "#fff0b0"], ground: "#587747", mood: "solar", backdrop: "level-12", bonus: true },
  ];

  const ITEM_CATEGORIES = {
    item: "Items",
  };

  const HAND_ITEMS = [
    { id: "lanternGear", category: "item", style: "lantern", name: "Grubenlampe", price: 10, mark: "☼", color: "#d99534", description: "Eine traditionelle Lampe mit warmem Licht für dunkle Stollen." },
    { id: "flashlight", category: "item", style: "flashlight", name: "Taschenlampe", price: 12, mark: "⌁", color: "#4f6875", description: "Eine handliche Lampe mit einem hellen Lichtkegel." },
    { id: "cane", category: "item", style: "cane", name: "Wanderstock", price: 9, mark: "╱", color: "#9b6b3d", description: "Ein geschnitzter Holzstock für Schorschs Bergwanderungen." },
    { id: "fiberCable", category: "item", style: "fiber", name: "Glasfaserkabel", price: 15, mark: "◎", color: "#20a8ce", description: "Eine leuchtend blaue Kabelrolle mit funkelndem Anschluss." },
    { id: "solarLamp", category: "item", style: "solar", name: "Solar-Lampe", price: 17, mark: "▣", color: "#2c7894", description: "Eine tragbare Leuchte mit kleinem Solarmodul auf der Oberseite." },
  ];

  const LEGACY_OUTFIT_REFUNDS = {
    cape: 8, forestJacket: 11, minerJacket: 14, winterJacket: 18,
    hat: 10, redBeanie: 12, minerCap: 15, winterHat: 17,
    hikingBoots: 9, redSneakers: 13, snowBoots: 16, scarf: 11,
  };

  const TALENTS = [
    { id: "highJump", name: "Federleicht", price: 12, mark: "↟", description: "Schorsch springt ein kleines Stück höher." },
    { id: "glide", name: "Wolkenritt", price: 14, mark: "☁", description: "Sprungtaste beim Fallen halten, um sanft zu gleiten." },
    { id: "magnet", name: "Kristallblick", price: 10, mark: "◇", description: "Bergfunken in der Nähe finden von allein zu Schorsch." },
    { id: "extraHeart", name: "Wanderherz", price: 12, mark: "♥", description: "Das erste gefundene Wanderherz jedes Levels zählt doppelt." },
    { id: "secretPaths", name: "Spurensucher", price: 8, mark: "✦", description: "Geheime Wege werden mit kleinen Sternen markiert." },
    { id: "trailRunner", name: "Bergsprinter", price: 13, mark: "➜", description: "Schorsch läuft etwas schneller und beschleunigt flotter." },
    { id: "safetyNet", name: "Wanderseil", price: 16, mark: "⌁", description: "Fängt einmal pro Level einen Sturz ab – ohne ein Leben zu kosten." },
  ];

  const CAMPAIGN_CHAPTERS = [
    {
      mark: "★",
      title: "Die Werkstatt braucht Hilfe",
      shortTitle: "Holzsterne einsammeln",
      tutorial: "Drei geschnitzte Holzsterne sind auf dem Waldweg verloren gegangen. Sammle sie ein und bringe sie zur Werkstatt am Ziel.",
      controls: "Laufe einfach durch die gold markierten Holzsterne. Der Auftragsbalken zeigt deinen Fortschritt.",
      objective: "Finde 3 Werkstattsterne",
      objectiveDone: "Alle Werkstattsterne gefunden",
      nodeNames: ["Stern vom Waldweg", "Stern vom Dorfplatz", "Stern vom Höhenpfad"],
      finalTitle: "Werkstatt-Finale",
      finalHint: "Setze die drei Sterne an der Werkbank zusammen. Bleibe kurz am Tisch stehen, bis der Schwibbogen leuchtet.",
      finalActive: "Schwibbogen zusammensetzen",
      finalDone: "Der Schwibbogen leuchtet",
      taskStyle: "star",
      finaleType: "charge",
      finaleStyle: "workshop",
      accent: "#e1ad45",
      nodeRatios: [.31, .56, .76],
      finalDistance: 520,
    },
    {
      mark: "✦",
      title: "Das Dorf soll wieder leuchten",
      shortTitle: "Lichter anzünden",
      tutorial: "Im Dorf der Lichter sind drei Festlaternen erloschen. Entzünde sie auf deinem Weg. Hinter dem Lichterlauf erwacht der Kristallwächter.",
      controls: "Berühre jede Laterne, durchquere die drei Lichtringe und springe danach dreimal von oben auf den Kristallwächter.",
      objective: "Entzünde 3 Festlaternen",
      objectiveDone: "Alle Festlaternen brennen",
      nodeNames: ["Werkstattlaterne", "Marktlaterne", "Berglaterne"],
      finalTitle: "Lichterlauf-Finale",
      finalHint: "Durchquere die drei Lichtringe und besiege danach den Kristallwächter mit drei Sprüngen von oben.",
      finalActive: "Lichterlauf und Wächter bezwingen",
      finalDone: "Kristallwächter besiegt · Lichterbogen entzündet",
      taskStyle: "lantern",
      finaleType: "sequence",
      finaleStyle: "lights",
      accent: "#efbd4f",
      nodeRatios: [.24, .49, .72],
      finalDistance: 1450,
      duration: 30,
      bossName: "Kristallwächter",
      bossKind: "crystalGuardian",
      bossHits: 3,
      bossAfterMechanic: true,
    },
    {
      mark: "◆",
      title: "Sichere den Silberstollen",
      shortTitle: "Stützen verriegeln",
      tutorial: "Drei alte Grubenstützen haben sich gelöst. Verriegle ihre Kurbeln in der richtigen Reihenfolge und sichere den Weg zum Ausgang.",
      controls: "Folge den Zahlen 1 bis 3. Eine Kurbel reagiert erst, wenn die vorherige Stütze gesichert ist.",
      objective: "Verriegle 3 Grubenstützen",
      objectiveDone: "Der Stollen ist gesichert",
      nodeNames: ["Eingangsstütze", "Kristallstütze", "Tiefenstütze"],
      finalTitle: "Lorenflucht-Finale",
      finalHint: "Sobald du die Warnlinie überquerst, setzt sich eine alte Lore in Bewegung. Erreiche rechtzeitig den Ausgang.",
      finalActive: "Der Lore entkommen",
      finalDone: "Sicher aus dem Stollen entkommen",
      taskStyle: "support",
      finaleType: "escape",
      finaleStyle: "cart",
      sequential: true,
      sequenceReminder: "Zuerst Stütze {next} verriegeln.",
      failureMessage: "Die Lore war schneller – versuche die Flucht noch einmal!",
      retryCostsLife: true,
      accent: "#73b9c5",
      nodeRatios: [.22, .48, .69],
      finalDistance: 1550,
      duration: 18,
    },
    {
      mark: "≈",
      title: "Bring die Zschopau-Mühlen in Gang",
      shortTitle: "Mühlräder ausrichten",
      tutorial: "Drei Mühlräder stehen quer zur Strömung. Richte ihre Schaufeln aus, damit das Wasser wieder gleichmäßig durch das Tal fließt.",
      controls: "Berühre jedes türkis markierte Mühlrad. Die Reihenfolge ist frei.",
      objective: "Richte 3 Mühlräder aus",
      objectiveDone: "Alle Mühlräder laufen",
      nodeNames: ["Waldmühle", "Brückenmühle", "Talmühle"],
      finalTitle: "Stromschnellen-Finale",
      finalHint: "Durchquere die drei Wassertore, bevor die Strömung wieder anschwillt.",
      finalActive: "Wassertore durchqueren",
      finalDone: "Die Zschopau fließt ruhig",
      taskStyle: "wheel",
      finaleType: "sequence",
      finaleStyle: "water",
      accent: "#45b5c4",
      nodeRatios: [.23, .47, .69],
      finalDistance: 1500,
      duration: 19,
      failureMessage: "Die Strömung war zu stark – die Wassertore öffnen sich erneut.",
    },
    {
      mark: "●",
      title: "Mach die Bimmelbahn fahrbereit",
      shortTitle: "Bahnsignale stellen",
      tutorial: "Vor der Abfahrt müssen drei Streckensignale auf Grün stehen. Schalte sie entlang der Strecke in Fahrtrichtung frei.",
      controls: "Aktiviere die nummerierten Signale von 1 bis 3. Ein falsches Signal wartet auf seinen Vorgänger.",
      objective: "Stelle 3 Signale auf Grün",
      objectiveDone: "Die Strecke ist freigegeben",
      nodeNames: ["Waldsignal", "Weichensignal", "Depotsignal"],
      finalTitle: "Fahrplan-Finale",
      finalHint: "Passiere die drei Taktmarken rechtzeitig, damit die Bimmelbahn pünktlich abfahren kann.",
      finalActive: "Den Fahrplan halten",
      finalDone: "Die Bimmelbahn fährt pünktlich",
      taskStyle: "signal",
      finaleType: "sequence",
      finaleStyle: "train",
      sequential: true,
      sequenceReminder: "Zuerst Signal {next} auf Grün stellen.",
      accent: "#cf6260",
      nodeRatios: [.21, .46, .7],
      finalDistance: 1550,
      duration: 18,
      failureMessage: "Der Fahrplan ist verpasst – die Taktmarken werden neu gestellt.",
    },
    {
      mark: "↗",
      title: "Sichere die Annaberger Dächer",
      shortTitle: "Wetterfahnen ausrichten",
      tutorial: "Ein kräftiger Höhenwind hat drei Wetterfahnen verdreht. Richte sie aus, bevor der nächste Windstoß über die Dächer zieht. Am letzten First wartet die Sturmkrähe.",
      controls: "Berühre die kupferfarbenen Wetterfahnen. Springe im Finale dreimal von oben auf die Sturmkrähe.",
      objective: "Richte 3 Wetterfahnen aus",
      objectiveDone: "Alle Wetterfahnen zeigen richtig",
      nodeNames: ["Gassenfahne", "Kirchfahne", "Firstfahne"],
      finalTitle: "Dachsturm-Finale",
      finalHint: "Überquere den letzten Dachabschnitt und besiege die Sturmkrähe mit drei Sprüngen von oben.",
      finalActive: "Dem Dachsturm entkommen",
      finalDone: "Die Dächer sind sicher",
      taskStyle: "weatherVane",
      finaleType: "escape",
      finaleStyle: "wind",
      accent: "#cf7b5f",
      nodeRatios: [.25, .5, .71],
      finalDistance: 1500,
      duration: 36,
      bossName: "Sturmkrähe",
      bossKind: "stormCrow",
      bossHits: 3,
      failureMessage: "Die Sturmkrähe war schneller – beginne den Dachspurt noch einmal.",
    },
    {
      mark: "♨",
      title: "Entzünde den großen Schwibbogen",
      shortTitle: "Bogenkerzen entzünden",
      tutorial: "Drei besondere Bogenkerzen fehlen noch für das nächtliche Lichterfest. Entzünde sie auf deinem Weg.",
      controls: "Berühre die markierten Kerzen. Jede entzündete Flamme weist dir anschließend den Weg.",
      objective: "Entzünde 3 Bogenkerzen",
      objectiveDone: "Alle Bogenkerzen brennen",
      nodeNames: ["Fensterkerze", "Stollenkerze", "Gipfelkerze"],
      finalTitle: "Lichtkreis-Finale",
      finalHint: "Bleibe im Lichtkreis, bis der große Schwibbogen vollständig erstrahlt.",
      finalActive: "Den Lichtkreis füllen",
      finalDone: "Der große Schwibbogen leuchtet",
      taskStyle: "candle",
      finaleType: "charge",
      finaleStyle: "arch",
      accent: "#efc357",
      nodeRatios: [.22, .48, .73],
      finalDistance: 590,
    },
    {
      mark: "▲",
      title: "Markiere den Greifenstein-Pfad",
      shortTitle: "Steinzeichen errichten",
      tutorial: "Nebel zieht zwischen den Felsen auf. Richte drei Steinzeichen auf, damit Wanderer den sicheren Höhenpfad erkennen.",
      controls: "Berühre die hell umrandeten Steinhaufen. Fertige Zeichen tragen anschließend eine Fahne.",
      objective: "Errichte 3 Steinzeichen",
      objectiveDone: "Der Höhenpfad ist markiert",
      nodeNames: ["Talzeichen", "Felstor-Zeichen", "Aussichtszeichen"],
      finalTitle: "Felstor-Finale",
      finalHint: "Durchquere die drei Felstore, bevor der Nebel den Pfad wieder verdeckt.",
      finalActive: "Durch die Felstore klettern",
      finalDone: "Die Greifensteine sind bezwungen",
      taskStyle: "cairn",
      finaleType: "sequence",
      finaleStyle: "rocks",
      accent: "#b59672",
      nodeRatios: [.24, .48, .7],
      finalDistance: 1500,
      duration: 20,
      failureMessage: "Der Nebel ist zurück – die Felstore erscheinen erneut.",
    },
    {
      mark: "⚿",
      title: "Öffne das Wolkensteiner Uhrwerk",
      shortTitle: "Burgschlüssel finden",
      tutorial: "Das alte Burguhrwerk ist stehen geblieben. Drei Schlüssel auf dem Höhenweg öffnen seinen Mechanismus.",
      controls: "Sammle die violett-goldenen Schlüssel. Jeder Schlüssel öffnet ein weiteres Zahnrad.",
      objective: "Finde 3 Uhrwerkschlüssel",
      objectiveDone: "Alle Uhrwerkschlüssel gefunden",
      nodeNames: ["Torschlüssel", "Turmschlüssel", "Uhrwerkschlüssel"],
      finalTitle: "Uhrwerk-Finale",
      finalHint: "Bleibe an der Kurbel, bis das große Burgzahnrad wieder gleichmäßig läuft.",
      finalActive: "Das Uhrwerk aufziehen",
      finalDone: "Die Burguhr schlägt wieder",
      taskStyle: "key",
      finaleType: "charge",
      finaleStyle: "clock",
      accent: "#a58ac9",
      nodeRatios: [.23, .49, .72],
      finalDistance: 610,
    },
    {
      mark: "⚑",
      title: "Bereite den Fichtelberg-Gipfel vor",
      shortTitle: "Gipfelwimpel hissen",
      tutorial: "Für die Ankunft am Gipfel fehlen drei Wegwimpel. Hisse sie für den letzten Anstieg. Vor dem Gipfeltor wartet der Wolkentitan.",
      controls: "Berühre jeden roten Wimpel. Besiege im Finale den Wolkentitan mit vier Sprüngen von oben.",
      objective: "Hisse 3 Gipfelwimpel",
      objectiveDone: "Der Gipfelweg ist markiert",
      nodeNames: ["Waldgrenz-Wimpel", "Wolken-Wimpel", "Gipfel-Wimpel"],
      finalTitle: "Gipfelsturm-Finale",
      finalHint: "Stürme zum Gipfeltor und bezwinge den Wolkentitan mit vier Sprüngen, bevor er den Gipfel verhüllt.",
      finalActive: "Gipfelsturm und Titan bezwingen",
      finalDone: "Wolkentitan besiegt · Fichtelberg erreicht",
      taskStyle: "flag",
      finaleType: "escape",
      finaleStyle: "avalanche",
      accent: "#db6764",
      nodeRatios: [.22, .47, .7],
      finalDistance: 1650,
      duration: 42,
      bossName: "Wolkentitan",
      bossKind: "cloudTitan",
      bossHits: 4,
      failureMessage: "Die Wolkenfront hat aufgeholt – starte den Gipfelspurt zum Wolkentitan erneut.",
    },
    {
      mark: "◉",
      title: "Entlaste den gefluteten Stollen",
      shortTitle: "Druckventile öffnen",
      tutorial: "Im gefluteten Stollen steigt der Wasserdruck. Öffne drei alte Ventile in der richtigen Reihenfolge.",
      controls: "Tauche zu den nummerierten Ventilen 1 bis 3. Mit W/↑ steigst du auf, mit S/↓ tauchst du ab.",
      objective: "Öffne 3 Druckventile",
      objectiveDone: "Der Wasserdruck ist stabil",
      nodeNames: ["Oberes Ventil", "Tiefenventil", "Auslassventil"],
      finalTitle: "Druckwellen-Finale",
      finalHint: "Tauche rechtzeitig durch die drei Druckringe und erreiche den Stollenausgang.",
      finalActive: "Druckringe durchtauchen",
      finalDone: "Der Stollen ist entlastet",
      taskStyle: "valve",
      finaleType: "sequence",
      finaleStyle: "dive",
      sequential: true,
      sequenceReminder: "Zuerst Ventil {next} öffnen.",
      accent: "#5de0df",
      nodeRatios: [.21, .47, .69],
      nodeYRatios: [.3, .72, .42],
      finaleYRatios: [.7, .28, .52],
      finalDistance: 1420,
      duration: 22,
      failureMessage: "Die Druckwelle ist abgeklungen – die Ringe öffnen sich erneut.",
    },
    {
      mark: "☀",
      title: "Lade die Sonnenbahn",
      shortTitle: "Solarmodule ausrichten",
      tutorial: "Drei Solarmodule liefern noch nicht genug Energie für die Heimfahrt. Richte sie zur Sonne aus.",
      controls: "Berühre die blau-goldenen Solarmodule. Die Ladeanzeige wächst mit jedem ausgerichteten Feld.",
      objective: "Richte 3 Solarmodule aus",
      objectiveDone: "Alle Solarmodule liefern Energie",
      nodeNames: ["Wiesenmodul", "Hangmodul", "Bahnhofsmodul"],
      finalTitle: "Ladestation-Finale",
      finalHint: "Bleibe an der Ladestation, bis die Sonnenbahn vollständig aufgeladen ist.",
      finalActive: "Die Sonnenbahn aufladen",
      finalDone: "Die Sonnenbahn ist fahrbereit",
      taskStyle: "solar",
      finaleType: "charge",
      finaleStyle: "solar",
      accent: "#f0bd4f",
      nodeRatios: [.22, .49, .72],
      finalDistance: 620,
    },
  ];

  const LEVEL_MUSIC = [
    { name: "Seiffener Werkstatttanz", tempo: 108, meter: 8, root: 62, mode: "major", lead: "zither", rhythm: "polka", progression: [0, 5, 7, 0], melody: [0, 4, 7, 4, 2, 0, -3, null, 0, 2, 4, 7, 4, 2, 0, null] },
    { name: "Lichterdorfer Walzer", tempo: 96, meter: 6, root: 67, mode: "major", lead: "accordion", rhythm: "waltz", progression: [0, 5, 7, 0], melody: [0, 2, 4, 7, 4, 2, 0, null, 4, 7, 9, 7, 5, 4, 2, null, 0, 2] },
    { name: "Stollenweise", tempo: 84, meter: 8, root: 62, mode: "minor", lead: "clarinet", rhythm: "march", progression: [0, 3, 5, 0], melody: [0, 3, 5, 7, 5, 3, 0, null, -2, 0, 3, 5, 3, 0, -2, null] },
    { name: "Zschopauer Wasserlied", tempo: 104, meter: 8, root: 60, mode: "major", lead: "flute", rhythm: "flow", progression: [0, 5, 2, 7], melody: [0, 2, 4, 7, 9, 7, 4, 2, 0, 4, 5, 9, 7, 5, 4, null] },
    { name: "Bimmelbahn-Polka", tempo: 122, meter: 8, root: 67, mode: "major", lead: "accordion", rhythm: "polka", progression: [0, 7, 5, 0], melody: [0, 4, 7, null, 7, 9, 7, 4, 2, 5, 9, null, 7, 4, 2, null] },
    { name: "Annaberger Dachwalzer", tempo: 92, meter: 6, root: 69, mode: "minor", lead: "strings", rhythm: "waltz", progression: [0, 5, 3, 7], melody: [0, 3, 7, 8, 7, 3, 0, null, -2, 0, 3, 5, 3, 0, -2, null, 0, 3] },
    { name: "Lichterbogen-Nocturne", tempo: 78, meter: 6, root: 64, mode: "minor", lead: "bell", rhythm: "waltz", progression: [0, 3, 7, 5], melody: [0, 3, 7, 10, 7, 3, 2, null, 5, 7, 10, 12, 10, 7, 5, null, 3, 2] },
    { name: "Greifenstein-Marsch", tempo: 112, meter: 8, root: 65, mode: "major", lead: "dulcimer", rhythm: "march", progression: [0, 5, 7, 0], melody: [0, 0, 5, 4, 2, 4, 7, null, 7, 5, 4, 2, 0, 2, 0, null] },
    { name: "Wolkensteiner Menuett", tempo: 100, meter: 6, root: 62, mode: "major", lead: "flute", rhythm: "minuet", progression: [0, 7, 5, 0], melody: [0, 4, 7, 9, 7, 4, 2, 5, 9, 11, 9, 5, 4, 2, 0, 2, 4, null] },
    { name: "Fichtelberger Gipfelreigen", tempo: 116, meter: 8, root: 67, mode: "major", lead: "horn", rhythm: "march", progression: [0, 5, 2, 7], melody: [0, 4, 7, 12, 11, 9, 7, null, 5, 9, 12, 14, 12, 9, 7, null] },
    { name: "Tauchstollen-Wasserweise", tempo: 82, meter: 8, root: 60, mode: "dorian", lead: "flute", rhythm: "flow", progression: [0, 3, 7, 5], melody: [0, 2, 3, 7, 9, 7, 5, 3, 0, -2, 0, 3, 5, 7, 3, null] },
    { name: "Sonnenbahn-Polka", tempo: 118, meter: 8, root: 65, mode: "major", lead: "accordion", rhythm: "polka", progression: [0, 5, 7, 0], melody: [0, 4, 7, 9, 7, 4, 2, null, 5, 9, 12, 9, 7, 4, 2, null] },
  ];

  const SECRET_MOTIFS = [
    [0, 3, 7, 5, 3, 0, -2, null, 0, 5, 7, 10, 7, 5, 3, null],
    [0, 2, 6, 9, 6, 2, 0, null, 3, 6, 8, 6, 3, 2, 0, null],
    [0, 3, 5, 8, 7, 5, 3, null, -2, 0, 5, 7, 5, 3, 0, null],
    [0, 2, 5, 7, 9, 7, 5, 2, 0, -2, 0, 5, 7, 5, 2, null],
    [0, 3, 7, null, 5, 8, 7, 3, 0, 5, 10, null, 8, 7, 5, null],
    [0, 3, 5, 10, 8, 5, 3, 0, -2, 3, 7, 8, 7, 3, 0, null],
    [0, 2, 5, 8, 11, 8, 5, null, 3, 5, 8, 10, 8, 5, 2, null],
    [0, 5, 3, 7, 5, 10, 7, null, 0, 3, 8, 7, 5, 3, 0, null],
    [0, 3, 7, 11, 7, 5, 3, null, 2, 5, 8, 10, 8, 5, 3, null],
    [0, 2, 7, 9, 12, 9, 7, null, 5, 7, 10, 14, 12, 10, 7, null],
  ];
  const SECRET_MUSIC_NAMES = [
    "Federwerkstatt-Galopp", "Lichterkeller-Flüstern", "Kristallaufzug-Kanon", "Grotten-Tropfenlied", "Zugdepot-Schleichpolka",
    "Dacharchiv-Nachtwalzer", "Laternenlabyrinth-Reigen", "Granitschacht-Echo", "Uhrwerk-Menuett", "Gipfelhöhlen-Finale",
  ];

  const SECRET_MUSIC = SECRET_MOTIFS.map((melody, index) => ({
    name: SECRET_MUSIC_NAMES[index],
    tempo: 86 + index * 2,
    meter: index % 3 === 1 ? 6 : 8,
    root: 57 + (index % 5),
    mode: index % 4 === 3 ? "dorian" : "minor",
    lead: ["bell", "clarinet", "zither", "flute"][index % 4],
    rhythm: "secret",
    progression: [0, 3, 5, 7],
    melody,
    secret: true,
  }));

  const REGIONAL_ITEMS = {
    forest: { name: "Seiffener Holzstern", type: "star", color: "#e2a446" },
    village: { name: "Lichterfigur", type: "figure", color: "#e9b94e" },
    mine: { name: "Kleine Grubenlampe", type: "lantern", color: "#f0a83c" },
    river: { name: "Zschopau-Mühlentaler", type: "coin", color: "#56a7b5" },
    rail: { name: "Bimmelbahn-Fahrkarte", type: "ticket", color: "#b9514d" },
    rooftops: { name: "Annaberger Schieferherz", type: "heart", color: "#667b87" },
    night: { name: "Schwibbogen-Kerze", type: "candle", color: "#f0bd53" },
    rocks: { name: "Greifenstein-Abzeichen", type: "badge", color: "#8d755a" },
    castle: { name: "Wolkensteiner Schlüssel", type: "key", color: "#d4a445" },
    summit: { name: "Fichtelberg-Wimpel", type: "flag", color: "#c55659" },
    underwater: { name: "Versunkene Grubenmarke", type: "coin", color: "#63dbe2" },
  };

  const SECRET_ROOM_LAYOUTS = [
    {
      name: "Federwerkstatt", mood: "forest", backdrop: "mine", special: "spring-workshop",
      mechanic: "Federketten und laufende Werkbänke", worldWidth: 2250, groundType: "mine", ledgeType: "wood",
      grounds: [[0,620,350],[470,600,300],[890,635,315],[1330,590,300],[1765,620,485]],
      ledges: [[235,500,140,"wood",null,{conveyor:80}],[430,405,130,"wood"],[635,310,145,"wood",{axis:"y",range:42,speed:.75}],[850,455,150,"mine"],[1080,355,145,"wood"],[1295,265,140,"wood",{axis:"x",range:45,speed:.65}],[1540,430,150,"mine"],[1740,330,145,"wood"],[1980,455,160,"wood",null,{conveyor:-70}]],
      springs: [[285,602],[705,582],[1120,617],[1510,572]], hazards: [[1010,600,55,.8],[1880,586,65,.9]],
    },
    {
      name: "Lichterkeller", mood: "night", backdrop: "night", special: "light-bridges",
      mechanic: "Sanft pulsierende Lichtbrücken", worldWidth: 2420, groundType: "earth", ledgeType: "roof",
      grounds: [[0,620,410],[560,635,270],[990,605,320],[1470,630,290],[1910,610,510]],
      ledges: [[260,505,135,"roof"],[455,410,130,"roof",null,{toggle:{period:3.6,phase:0}}],[675,330,140,"roof",null,{toggle:{period:3.6,phase:1.8}}],[885,450,140,"stone"],[1110,355,145,"roof",null,{toggle:{period:4.2,phase:.8}}],[1340,270,135,"roof"],[1585,430,150,"roof",null,{toggle:{period:4.2,phase:2.9}}],[1810,340,140,"stone"],[2070,465,170,"roof"]],
      springs: [[330,602],[1200,587]], hazards: [[705,602,48,.72],[1600,596,55,.83]],
    },
    {
      name: "Kristallaufzüge", mood: "mine", backdrop: "mine", special: "crystal-lifts",
      mechanic: "Hohe Schächte und Kristallaufzüge", worldWidth: 2550, groundType: "mine", ledgeType: "mine",
      grounds: [[0,620,360],[520,640,300],[980,625,290],[1440,640,320],[1940,615,610]],
      ledges: [[240,500,135,"mine",{axis:"y",range:65,speed:.55}],[450,385,130,"mine"],[650,270,135,"wood",{axis:"y",range:82,speed:.48}],[875,410,145,"mine"],[1085,285,135,"mine",{axis:"y",range:72,speed:.6}],[1320,195,140,"wood"],[1545,360,145,"mine",{axis:"x",range:70,speed:.55}],[1775,255,145,"mine",{axis:"y",range:75,speed:.52}],[2070,430,175,"wood"]],
      springs: [[285,602],[1510,622]], hazards: [[670,606,55,.8],[2170,581,80,.9]],
    },
    {
      name: "Zschopau-Grotte", mood: "river", backdrop: "mine", special: "water-grotto",
      mechanic: "Wasserströmungen und schwimmende Stege", worldWidth: 2380, groundType: "earth", ledgeType: "wood",
      grounds: [[0,620,390],[535,635,310],[1010,615,270],[1435,640,300],[1890,610,490]],
      ledges: [[250,505,155,"wood",{axis:"y",range:20,speed:1.1}],[475,420,145,"wood",{axis:"y",range:28,speed:.95}],[700,335,150,"wood",{axis:"x",range:55,speed:.55}],[915,455,140,"stone"],[1120,360,145,"wood",{axis:"y",range:25,speed:1.05}],[1340,270,145,"wood"],[1580,425,150,"wood",{axis:"x",range:60,speed:.58}],[1800,330,145,"stone"],[2040,465,170,"wood"]],
      springs: [[305,602],[1195,597]], hazards: [[690,601,55,.7],[1590,606,60,.82]], currents: [[535,310,115],[1435,300,-105]],
    },
    {
      name: "Verlassenes Zugdepot", mood: "rail", backdrop: "day", special: "train-depot",
      mechanic: "Bewegliche Holzstege im alten Zugdepot", worldWidth: 2720, groundType: "earth", ledgeType: "wood",
      grounds: [[0,620,360],[620,630,260],[1110,610,310],[1660,635,270],[2170,610,550]],
      ledges: [[290,500,210,"wood",{axis:"x",range:85,speed:.42}],[550,395,145,"wood"],[780,300,205,"stone",{axis:"x",range:110,speed:.38}],[1040,440,145,"wood"],[1280,340,210,"wood",{axis:"x",range:100,speed:.46}],[1550,250,145,"wood"],[1800,420,210,"stone",{axis:"x",range:95,speed:.4}],[2070,330,150,"wood"],[2350,455,220,"wood",{axis:"x",range:70,speed:.45}]],
      springs: [[300,602],[1295,592]], hazards: [[735,596,42,.82],[2290,576,75,.9]],
    },
    {
      name: "Annaberger Dacharchiv", mood: "rooftops", backdrop: "night", special: "roof-wind",
      mechanic: "Schmale Schieferdächer und Schornsteinwind", worldWidth: 2350, groundType: "earth", ledgeType: "roof",
      grounds: [[0,620,390],[530,610,280],[950,625,300],[1390,605,280],[1820,620,530]],
      ledges: [[220,500,155,"roof"],[415,405,145,"roof"],[610,315,140,"roof"],[805,225,135,"roof"],[1010,365,150,"roof"],[1220,275,140,"roof"],[1430,185,135,"roof"],[1660,330,150,"roof"],[1950,450,185,"roof"]],
      springs: [[315,602],[1075,607]], hazards: [[695,576,50,.75],[1950,586,70,.88]], wind: [[600,420,80],[1380,390,-70]],
    },
    {
      name: "Laternenlabyrinth", mood: "night", backdrop: "night", special: "lantern-maze",
      mechanic: "Zwei Wege zwischen wechselnden Laternen", worldWidth: 2600, groundType: "earth", ledgeType: "wood",
      grounds: [[0,620,330],[500,640,260],[930,615,280],[1370,640,270],[1810,615,280],[2250,625,350]],
      ledges: [[230,500,135,"wood"],[410,390,130,"wood",null,{toggle:{period:4.8,phase:0}}],[610,280,135,"wood",null,{toggle:{period:4.8,phase:2.4}}],[820,470,140,"stone"],[1040,350,140,"wood",null,{toggle:{period:4,phase:1}}],[1250,245,135,"wood"],[1470,455,140,"wood",null,{toggle:{period:4,phase:3}}],[1690,335,140,"stone"],[1910,235,135,"wood",null,{toggle:{period:5,phase:1.6}}],[2140,430,150,"wood"],[2360,325,145,"wood"]],
      springs: [[275,602],[1515,622]], hazards: [[625,606,45,.8],[1900,581,55,.93]],
    },
    {
      name: "Greifenstein-Schacht", mood: "rocks", backdrop: "mine", special: "granite-climb",
      mechanic: "Eine hohe Zickzack-Kletterpassage", worldWidth: 2200, groundType: "mine", ledgeType: "stone",
      grounds: [[0,620,360],[520,640,260],[940,630,260],[1380,640,260],[1800,615,400]],
      ledges: [[250,520,110,"stone"],[430,440,105,"stone"],[590,355,105,"stone"],[430,270,105,"stone"],[650,190,110,"stone"],[870,300,115,"stone"],[1060,210,110,"stone"],[1260,330,115,"stone"],[1460,240,110,"stone"],[1660,350,120,"stone"],[1900,455,160,"stone"]],
      springs: [[300,602],[1010,612]], hazards: [[650,606,42,.76],[1510,606,48,.88]],
    },
    {
      name: "Wolkensteiner Uhrwerk", mood: "castle", backdrop: "night", special: "clockwork",
      mechanic: "Gegenläufige Zahnräder und Förderbänder", worldWidth: 2500, groundType: "mine", ledgeType: "wood",
      grounds: [[0,620,380],[520,630,300],[980,610,290],[1430,635,300],[1890,610,610]],
      ledges: [[240,500,155,"wood",null,{conveyor:95}],[460,405,140,"wood",{axis:"x",range:65,speed:.8}],[690,310,145,"wood",{axis:"y",range:55,speed:.7}],[910,450,140,"mine"],[1120,350,155,"wood",null,{conveyor:-105}],[1370,255,145,"wood",{axis:"x",range:75,speed:.72}],[1600,420,150,"mine"],[1820,315,145,"wood",{axis:"y",range:60,speed:.68}],[2100,455,180,"wood",null,{conveyor:90}]],
      springs: [[300,602],[1160,592]], hazards: [[680,596,55,.9],[2070,576,75,1]],
    },
    {
      name: "Fichtelberger Gipfelhöhle", mood: "summit", backdrop: "night", special: "ice-wind",
      mechanic: "Rutschige Felsen, Aufwind und ein langer Finalsprung", worldWidth: 2820, groundType: "mine", ledgeType: "stone",
      grounds: [[0,620,410],[600,640,260],[1050,615,270],[1520,640,250],[1980,620,300],[2440,600,380]],
      ledges: [[285,505,145,"stone"],[510,410,135,"stone",{axis:"y",range:45,speed:.55}],[750,315,140,"stone"],[975,220,135,"stone"],[1210,360,145,"stone",{axis:"x",range:70,speed:.5}],[1450,260,140,"stone"],[1700,170,135,"stone"],[1950,320,145,"stone",{axis:"y",range:60,speed:.58}],[2190,225,140,"stone"],[2450,430,180,"stone"]],
      springs: [[345,602],[1115,597],[2060,602]], hazards: [[730,606,55,.85],[2100,586,70,.96]], wind: [[900,500,125],[1650,500,-90],[2250,400,145]],
    },
  ];


  Object.assign(window.SchorschGame ||= {}, {
    GAME_VERSION,
    LEVELS,
    ITEM_CATEGORIES,
    HAND_ITEMS,
    LEGACY_OUTFIT_REFUNDS,
    TALENTS,
    CAMPAIGN_CHAPTERS,
    LEVEL_MUSIC,
    SECRET_MUSIC,
    REGIONAL_ITEMS,
    SECRET_ROOM_LAYOUTS,
  });
})();
